export interface Order 
{
    id                          : string;
    storeId                     : string;
    subTotal                    : number;
    deliveryCharges             : number;
    total                       : number;
    completionStatus            : string;
    paymentStatus               : string;
    customerNotes               : string;
    privateAdminNotes           : string;
    cartId                      : string;
    customerId                  : string;
    created                     : string;
    updated                     : string;
    invoiceId                   : string;
    totalReminderSent           : string;
    klCommission                : number;
    storeServiceCharges         : number;
    storeShare                  : number;
    paymentType                 : string;
    deliveryType                : string;
    appliedDiscount             : number;
    deliveryDiscount            : number;
    voucherDiscount             : null,
    storeVoucherDiscount        : null,
    appliedDiscountDescription  : null,
    deliveryDiscountDescription : null,
    beingProcess                : false,
    discountId                  : string;
    discountCalculationType     : null,
    discountCalculationValue    : null,
    discountMaxAmount           : null,
    deliveryDiscountMaxAmount   : null,
    isRevised                   : null,
    voucherId                   : string;
    storeVoucherId              : string;
    orderGroupId                : string;
    totalDataObject             : null,
    orderRefund                 : []
}